EXAMPLES OF SQL QUERIES

Total Revenue:

SELECT SUM(total_price) AS Total_Revenue FROM pizza_sales
_______________________________________________________________________________________________________________________

Average Order Value:

SELECT SUM(total_price) / COUNT(DISTINCT order_id) AS Avg_Order_Value FROM pizza_sales
_______________________________________________________________________________________________________________________

Total Pizza Sold:

SELECT SUM(quantity) AS Total_Pizza_Sold FROM pizza_sales
_______________________________________________________________________________________________________________________

Total orders:

SELECT COUNT(DISTINCT order_id) AS Total_Orders FROM pizza_sales
_______________________________________________________________________________________________________________________

Average Pizzas per Order

SELECT CAST(CAST(SUM(quantity) AS DECIMAL(10, 2)) / 
CAST(COUNT(DISTINCT order_id) AS DECIMAL(10, 2)) AS DECIMAL(10, 2)) AS Avg_Pizzas_Per_Order FROM pizza_sales
_______________________________________________________________________________________________________________________

Daily Trend

SELECT DATENAME(DW, order_date) AS Order_Day, COUNT(DISTINCT order_id) AS Total_Orders
from pizza_sales
GROUP BY DATENAME(DW, order_date)
_______________________________________________________________________________________________________________________

Hourly Trend

SELECT DATEPART(HOUR, order_time) AS Order_Hours, COUNT(DISTINCT order_id) AS Total_Orders
from pizza_sales
GROUP BY DATEPART(HOUR, order_time)
_______________________________________________________________________________________________________________________

Pct of Sales by Category

SELECT pizza_category, SUM(total_price) AS Total_Sales, SUM(total_price) * 100 / 
(SELECT SUM(total_price) FROM pizza_sales WHERE MONTH(order_date) = 1) AS PCT
FROM pizza_sales
WHERE MONTH(order_date) = 1
GROUP BY pizza_category
_______________________________________________________________________________________________________________________

Percentage of Sales by Pizza Size

SELECT pizza_size, CAST(SUM(total_price) AS DECIMAL(10, 2)) AS Total_Sales, CAST(SUM(total_price) * 100 / 
(SELECT SUM(total_price) FROM pizza_sales WHERE DATEPART(QUARTER, order_date)=1) AS DECIMAL(10, 2)) AS PCT
FROM pizza_sales
WHERE DATEPART(QUARTER, order_date)=1
GROUP BY pizza_size
ORDER BY PCT DESC
_______________________________________________________________________________________________________________________

Total Pizza Sold by Category

SELECT pizza_category, SUM(quantity) AS Total_Pizzas_Sold
FROM pizza_sales
GROUP BY pizza_category
_______________________________________________________________________________________________________________________

Top 5 Best Seller Pizzas

SELECT TOP 5 pizza_name, SUM(quantity) as Total_Pizzas_Sold
from pizza_sales
GROUP BY pizza_name
ORDER BY SUM(quantity) DESC
_______________________________________________________________________________________________________________________

Bottom 5 Worst Seller Pizzas

SELECT TOP 5 pizza_name, SUM(quantity) as Total_Pizzas_Sold
from pizza_sales
WHERE MONTH(order_date)=1
GROUP BY pizza_name
ORDER BY SUM(quantity) ASC
_______________________________________________________________________________________________________________________